apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}

labels:
  {{- include "python-app.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.postgres.replicas }}

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: {{ required "postgres.image is required" .Values.postgres.image }}

          ports:
            - containerPort: 5432

          envFrom:
            - secretRef:
                name: postgres-secret

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc