apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}

labels:
  {{- include "python-app.labels" . | nindent 4 }}

type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_USER: {{ .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}