grafana:
  adminPassword: admin123

  service:
    type: ClusterIP

prometheus:
  service:
    type: ClusterIP

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true