grafana:
  adminPassword: admin123

  service:
    type: NodePort
    nodePort: 32000

prometheus:
  service:
    type: NodePort
    nodePort: 32090

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true