apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
    release: monitoring

spec:
  selector:
    matchLabels:
      app: backend

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s