[kube_control_plane]
master ansible_host=192.168.56.10

[kube_workers]
worker ansible_host=192.168.56.11

[kubernetes:children]
kube_control_plane
kube_workers

[kubernetes:vars]
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3