name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/ravindranathsingh/backend-app
  IMAGE_FRONTEND: ghcr.io/ravindranathsingh/frontend-app
  IMAGE_TAG: ${{ github.sha }}

jobs:

  helm-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint helm/

      - name: Helm Template
        run: helm template python-app helm/


  build-backend:
    runs-on: ubuntu-latest
    needs: helm-validation

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ secrets.GHCR_USERNAME }}" \
            --password-stdin

      # ---------------------------
      # BUILD BACKEND IMAGE
      # ---------------------------
      - name: Build Backend Image
        run: |
          docker build -t ${{ env.IMAGE_BACKEND }}:${{ env.IMAGE_TAG }} ./app/backend

      # ---------------------------
      # SCAN BACKEND IMAGE (LOCAL)
      # ---------------------------
      - name: Trivy Scan Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_BACKEND }}:${{ env.IMAGE_TAG }}

      # ---------------------------
      # TAG LATEST
      # ---------------------------
      - name: Tag Latest Backend
        run: |
          docker tag ${{ env.IMAGE_BACKEND }}:${{ env.IMAGE_TAG }} ${{ env.IMAGE_BACKEND }}:latest

      # ---------------------------
      # PUSH BACKEND
      # ---------------------------
      - name: Push Backend Image
        run: |
          docker push ${{ env.IMAGE_BACKEND }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_BACKEND }}:latest


  build-frontend:
    runs-on: ubuntu-latest
    needs: helm-validation

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ secrets.GHCR_USERNAME }}" \
            --password-stdin

      # ---------------------------
      # BUILD FRONTEND IMAGE
      # ---------------------------
      - name: Build Frontend Image
        run: |
          docker build -t ${{ env.IMAGE_FRONTEND }}:${{ env.IMAGE_TAG }} ./app/frontend

      # ---------------------------
      # SCAN FRONTEND IMAGE (LOCAL)
      # ---------------------------
      - name: Trivy Scan Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_FRONTEND }}:${{ env.IMAGE_TAG }}

      # ---------------------------
      # TAG LATEST
      # ---------------------------
      - name: Tag Latest Frontend
        run: |
          docker tag ${{ env.IMAGE_FRONTEND }}:${{ env.IMAGE_TAG }} ${{ env.IMAGE_FRONTEND }}:latest

      # ---------------------------
      # PUSH FRONTEND
      # ---------------------------
      - name: Push Frontend Image
        run: |
          docker push ${{ env.IMAGE_FRONTEND }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_FRONTEND }}:latest