name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/ravindranathsingh/backend-app
  IMAGE_FRONTEND: ghcr.io/ravindranathsingh/frontend-app

jobs:

  helm-lint:
    name: Helm Lint & Template Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint helm/

      - name: Helm Template Render
        run: helm template python-app helm/

  docker-build-backend:
    name: Build Backend Image
    runs-on: ubuntu-latest
    needs: helm-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate secrets exist
        run: |
          if [ -z "${{ secrets.GHCR_USERNAME }}" ]; then echo "GHCR_USERNAME missing"; exit 1; fi
          if [ -z "${{ secrets.GHCR_TOKEN }}" ]; then echo "GHCR_TOKEN missing"; exit 1; fi

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
          -u "${{ secrets.GHCR_USERNAME }}" \
          --password-stdin

      - name: Debug workspace
        run: ls -R

      - name: Build Backend Image
        run: |
          ls -R
          docker build -t $IMAGE_BACKEND:${{ github.sha }} ./app/backend

      - name: Push Backend Image
        run: docker push $IMAGE_BACKEND:${{ github.sha }}

  docker-build-frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    needs: helm-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Debug workspace
        run: ls -R

      - name: Build Frontend Image
        run: docker build -t $IMAGE_FRONTEND:${{ github.sha }} ./app/frontend

      - name: Push Frontend Image
        run: docker push $IMAGE_FRONTEND:${{ github.sha }}

  trivy-scan:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    needs: [docker-build-backend, docker-build-frontend]

    steps:
      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_BACKEND:${{ github.sha }}

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_FRONTEND:${{ github.sha }}